version: "3.9"

services:
  db:
    image: postgres:12
    container_name: postgres-server
    networks:
      - githubactions-backend-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - ./scripts/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: app
    networks:
      - githubactions-backend-network
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=postgres-server
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: app-container
    command: tail -f /dev/null  # Keeps the container running
    volumes:
      - .:/app
    ports:
      - "8000:8000"

networks:
  githubactions-backend-network:
    name: githubactions-backend-network