\set DB_NAME `echo "$POSTGRES_DB"`
\set DB_USER `echo "$POSTGRES_USER"`
\set DB_PASSWORD `echo "$POSTGRES_PASSWORD"`
CREATE USER :DB_USER WITH PASSWORD :'DB_PASSWORD';
CREATE DATABASE :DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE :DB_NAME TO :DB_USER;
ALTER ROLE :DB_USER CREATEDB;